version: '3.8'

services:

  django:
    container_name: django
    build: 
      context: ./src
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=admin_user_ap
      - POSTGRES_PASSWORD=ApUser01!
      - POSTGRES_DB=andamento_produzione_db

volumes:
    postgres_data:
      