version: '3.8'

services:

  django:
    container_name: django
    build: 
      context: ./src
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/usr/src/app/
    ports:
      - 8001:8000
    