# Generated by Django 4.2.3 on 2024-03-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('O', 'Office'), ('T', 'Testing'), ('V', 'Verify'), ('S', 'SMT'), ('W', 'Welding')], max_length=1),
        ),
    ]
