# Generated by Django 4.2.3 on 2024-05-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalog',
            options={'ordering': ['created_at'], 'verbose_name': 'DataLog', 'verbose_name_plural': 'DataLog'},
        ),
    ]
