# Generated by Django 4.2.3 on 2024-05-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_datalog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalog',
            name='user',
        ),
    ]
