# Generated by Django 4.2.3 on 2024-05-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_datalog_http_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='http_request',
            field=models.IntegerField(),
        ),
    ]
