# Generated by Django 4.2.3 on 2024-05-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_datalog_http_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='http_request',
            field=models.TextField(max_length=10),
        ),
    ]
