# Generated by Django 4.2.3 on 2024-05-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_datalog_http_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datalog',
            old_name='http_request',
            new_name='http_request_methods',
        ),
    ]
