# Generated by Django 4.2.3 on 2024-05-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_http_request_datalog_http_request_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='operation_type',
            field=models.TextField(default='Step', max_length=50),
        ),
    ]
