# Generated by Django 4.2.3 on 2024-05-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_datalog_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='operation_type',
            field=models.TextField(max_length=50),
        ),
    ]
