# Generated by Django 4.2.3 on 2024-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_datalog_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalog',
            name='action',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='http_request_methods',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='operation_type',
            field=models.CharField(max_length=50),
        ),
    ]
