# Generated by Django 4.2.3 on 2023-10-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0002_alter_board_created_at_alter_board_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='customer',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
