# Generated by Django 4.2.3 on 2023-10-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0003_board_customer_alter_board_board_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_img',
            field=models.ImageField(blank=True, default='img/no-image.jpg', null=True, upload_to='img'),
        ),
    ]
