# Generated by Django 4.2.3 on 2023-10-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0004_alter_board_board_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_img',
            field=models.ImageField(default='img/no-image.jpg', upload_to='img'),
        ),
    ]
