# Generated by Django 4.2.3 on 2023-10-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0005_alter_board_board_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
