# Generated by Django 4.2.3 on 2023-11-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0007_alter_board_board_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_test', to='produzione.order'),
        ),
    ]
