# Generated by Django 4.2.3 on 2023-11-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0008_alter_test_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='missing_component',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='test',
            name='non_compliance',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='test',
            name='note',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='test',
            name='serialnumber',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
