# Generated by Django 4.2.3 on 2024-01-11 12:01

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0009_alter_test_missing_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('step_type', models.CharField(choices=[('1', 'Verifica'), ('2', 'Smt'), ('3', 'Collaudo'), ('4', 'Saldatura Onda'), ('5', 'Saldatura selettiva'), ('6', 'Preformatura')], default='Verifica', max_length=50)),
                ('step_name', models.CharField(max_length=180)),
                ('step_description', models.CharField(max_length=180)),
                ('step_color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('step_order', models.IntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase', to='produzione.board')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
