# Generated by Django 4.2.3 on 2024-01-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0010_productionsteps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionsteps',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
