# Generated by Django 4.2.3 on 2024-01-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0011_alter_productionsteps_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionsteps',
            options={'verbose_name': 'Step', 'verbose_name_plural': 'Steps'},
        ),
        migrations.AlterField(
            model_name='productionsteps',
            name='step_type',
            field=models.CharField(choices=[('Verifica', 'Verifica'), ('Smt', 'Smt'), ('Collaudo', 'Collaudo'), ('Saldatura Onda', 'Saldatura Onda'), ('Saldatura selettiva', 'Saldatura selettiva'), ('Preformatura', 'Preformatura')], default='Verifica', max_length=50),
        ),
    ]
