# Generated by Django 4.2.3 on 2024-01-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0012_alter_productionsteps_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='shipping_missing_components',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
