# Generated by Django 4.2.3 on 2024-01-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0013_shipping_shipping_missing_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_customization',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
