# Generated by Django 4.2.3 on 2024-02-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0015_alter_order_order_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='missing_component',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='non_compliance',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='note',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='serialnumber',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
