# Generated by Django 4.2.3 on 2024-02-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0016_alter_test_missing_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='non_compliance',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
