# Generated by Django 4.2.3 on 2024-02-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0017_alter_test_non_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='firma',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='missing_component',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='note',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='serialnumber',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
