# Generated by Django 4.2.3 on 2024-02-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0018_test_firma_alter_test_missing_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='firma',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='smt',
            name='firma',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='verify',
            name='firma',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_missing_components',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='verify',
            name='changes_after_testing',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='verify',
            name='manual_work',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='verify',
            name='missing_component',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
