# Generated by Django 4.2.3 on 2024-02-12 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0019_shipping_firma_smt_firma_verify_firma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('soldering_type', models.BooleanField(default=False, null=True)),
                ('soldering_program', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('non_compliance', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('missing_component', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('firma', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('status', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='welding_test', to='produzione.order')),
            ],
            options={
                'verbose_name': 'Welding',
                'verbose_name_plural': 'Welding',
            },
        ),
    ]
