# Generated by Django 4.2.3 on 2024-02-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0020_welding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welding',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_welding', to='produzione.order'),
        ),
    ]
