# Generated by Django 4.2.3 on 2024-02-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0023_remove_smt_smt_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='smt',
            name='smt_date_create',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
