# Generated by Django 4.2.3 on 2024-02-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0024_smt_smt_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smt',
            name='smt_date_create',
        ),
    ]
