# Generated by Django 4.2.3 on 2024-02-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0025_remove_smt_smt_date_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionsteps',
            options={'ordering': ['step_order'], 'verbose_name': 'Step', 'verbose_name_plural': 'Steps'},
        ),
        migrations.AlterField(
            model_name='productionsteps',
            name='step_order',
            field=models.IntegerField(default=6000),
        ),
    ]
