# Generated by Django 4.2.3 on 2024-02-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0026_alter_productionsteps_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionsteps',
            name='step_order',
            field=models.IntegerField(blank=True, default=6000),
        ),
    ]
