# Generated by Django 4.2.3 on 2024-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0027_alter_productionsteps_step_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_img_bot',
            field=models.ImageField(default='img/no-image.jpg', upload_to='img'),
        ),
    ]
