# Generated by Django 4.2.3 on 2024-03-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0029_order_order_filetopographic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_filetopographic',
            field=models.FileField(default='', upload_to='topographic'),
        ),
    ]
