# Generated by Django 4.2.3 on 2024-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0030_alter_order_order_filetopographic'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='alert_info',
            field=models.CharField(default='', max_length=180),
        ),
    ]
