# Generated by Django 4.2.3 on 2024-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0031_board_alert_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='alert_info',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
