# Generated by Django 4.2.3 on 2024-03-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0032_alter_board_alert_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(default='2024-03-03'),
        ),
    ]
