# Generated by Django 4.2.3 on 2024-04-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0034_alter_order_order_filetopographic'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_bom',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='order_placement_pick_and_place',
            field=models.TextField(blank=True, default=''),
        ),
    ]
