# Generated by Django 4.2.3 on 2024-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0035_order_order_bom_order_order_placement_pick_and_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_placement_pick_and_place',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
