# Generated by Django 4.2.3 on 2024-05-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0037_order_order_file_gerber_order_order_file_odb'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_file_schematics',
            field=models.FileField(blank=True, default='', upload_to='schematics'),
        ),
    ]
