# Generated by Django 4.2.3 on 2024-05-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0038_order_order_file_schematics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_filetopographic',
            new_name='order_file_topographic',
        ),
    ]
