# Generated by Django 4.2.3 on 2024-04-22 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('announcement_type', models.CharField(choices=[('comunicato', 'comunicato'), ('avviso', 'avviso')], default='comunicato', max_length=50)),
                ('announcement_title', models.CharField(default='', max_length=50)),
                ('announcement_content', models.TextField()),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
    ]
