# Generated by Django 4.2.3 on 2024-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('comunicato', 'comunicato'), ('avviso', 'avviso')], default='comunicato', max_length=50),
        ),
    ]
