# Generated by Django 4.2.3 on 2024-02-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_announcement_announcement_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_content',
            field=models.TextField(),
        ),
    ]
